name: Build and Push Docker image

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup toolchain for cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Clippy
        run: cargo clippy --no-deps --release

      - name: Tests
        run: cargo test --release

  buildPush:
    if: success()
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: pushRelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Monotipe
          draft: false
          prerelease: true
